//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمیتوانید به این صفحه دسترسی داشته باشید.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمیتوانید این درخواست را ایجاد کنید.
        /// </summary>
        public static string CanNotCreateThisRequest {
            get {
                return ResourceManager.GetString("CanNotCreateThisRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سطح نمیتواند تکراری باشد.
        /// </summary>
        public static string DuplicatedLevel {
            get {
                return ResourceManager.GetString("DuplicatedLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این عنوان از قبل وجود دارد.
        /// </summary>
        public static string DuplicatedTitle {
            get {
                return ResourceManager.GetString("DuplicatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری تکراری است.
        /// </summary>
        public static string DuplicatedUsername {
            get {
                return ResourceManager.GetString("DuplicatedUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور اشتباه است.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این درخواست قبلا ارسال شده است.
        /// </summary>
        public static string IsSentBefore {
            get {
                return ResourceManager.GetString("IsSentBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطحی پیدا نشد.
        /// </summary>
        public static string LevelNotFound {
            get {
                return ResourceManager.GetString("LevelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوق دسترسی جدید ثبت شد.
        /// </summary>
        public static string NewPrivilege {
            get {
                return ResourceManager.GetString("NewPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحله دیگری برای ارسال وجود ندارد.
        /// </summary>
        public static string NoLevelForSend {
            get {
                return ResourceManager.GetString("NoLevelForSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات ورودی کافی نیست.
        /// </summary>
        public static string NotEnoughEntry {
            get {
                return ResourceManager.GetString("NotEnoughEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موردی پیدا نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشی پیدا نشد.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمیتوانید دو مرحله یکسان را پشت سر هم انتخاب کنید.
        /// </summary>
        public static string SameLevelIsSelected {
            get {
                return ResourceManager.GetString("SameLevelIsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ایجاد شده است.
        /// </summary>
        public static string Status_Created {
            get {
                return ResourceManager.GetString("Status_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ارسال شده است.
        /// </summary>
        public static string Status_Sent {
            get {
                return ResourceManager.GetString("Status_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات موفق.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوق دسترسی به روز شد.
        /// </summary>
        public static string UpdatePrivilege {
            get {
                return ResourceManager.GetString("UpdatePrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری پیدا نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
